before_install:
  - "sudo apt-get install python-virtualenv"
  - "virtualenv ./test-env/"
  - "./test-env/bin/pip install --upgrade pip"

install:
  - "./test-env/bin/pip install ."

script:
  - "./test-env/bin/trial dvol"
