FROM ubuntu:16.04

ENV LAST_UPDATED "Sat 26 Mar 2016 09:18:20 GMT"

RUN apt-get update && \
    apt-get install -y zfsutils-linux

# TODO to work on boot2docker, copy kernel sources as per
# https://github.com/boot2docker/boot2docker/blob/master/Dockerfile#L26
